version: '3.8'

services:
  overlay:
    build: .
    container_name: kort-overlay
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./overlay_links.json:/app/overlay_links.json
    environment:
      - DATABASE_URL=sqlite:///data/overlay.db
      - CONFIG_AUTH_USERNAME=${CONFIG_AUTH_USERNAME:-}
      - CONFIG_AUTH_PASSWORD=${CONFIG_AUTH_PASSWORD:-}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tenis.rule=Host(`tenis.dawidsuchodolski.pl`)"
      - "traefik.http.routers.tenis.entrypoints=https"
      - "traefik.http.routers.tenis.tls=true"
      - "traefik.http.services.tenis.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
